# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=1500),
        ),
    ]
