# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 18:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20171216_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='default', max_length=1500, validators=[django.core.validators.RegexValidator(regex='(\\w\\w*)( \\w\\w*)*')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
